[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'context_filetype.vim']
on_event = 'InsertEnter'
hook_source = '''
  call ddc#custom#patch_global('sources', ['around', 'eskk'])
  call ddc#custom#patch_global('sourceOptions', {
    \ '_': {
    \   'matchers': ['matcher_head'],
    \   'sorters' : ['sorter_rank'],
    \   'converters': ['converter_remove_overlap']
    \ },
    \ 'around': {'mark': 'A' },
    \ 'eskk': {'mark': 'eskk', 'matchers': [], 'sorters': [], 'minAutoCompleteLength': 1},
    \ 'nvim-lsp': {'mark': 'lsp', 'forceCompletionPattern': '\\.|:|->'},
    \ })
  call ddc#custom#patch_global('sourceParams', {
    \ 'nvim-lsp': {'useIcon': v:true},
    \ })
  call ddc#custom#patch_filetype(
    \ ['rust', 'c', 'cpp', 'python'], 'sources',
    \ ['nvim-lsp', 'vsnip', 'around', 'eskk']
    \ )
  call ddc#enable()
'''



[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = ['vim-vsnip']
on_source = 'ddc.vim'



# ddc sources
[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'nvim-lspconfig'
depends = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-nvim-lsp-doc'
on_source = 'ddc-nvim-lsp'
hook_source = '''
  call ddc_nvim_lsp_doc#enable()
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'toml', 'help']
depends = 'ddc.vim'
hook_source = '''
    call ddc#custom#patch_filetype(
      \ ['vim', 'toml', 'help'], 'sources',
      \ ['necovim', 'around', 'eskk']
      \ )
'''



# ddc matchers
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'


# ddc sorters
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'


# ddc converters
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'
