[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['vim-devicons']
hook_add = '''
  nmap [denite] <Nop>
  map <C-j> [denite]

  "カレントディレクトリ内のファイル検索"
  nmap <silent> [denite]<C-p> :<C-u>Denite -mode=normal file_rec
  "プレビュー付きgrep"
  nmap <silent> [denite]<C-g> :<C-u>Denite -auto-preview -mode=normal grep<CR>


  "検索対象外のファイル指定"
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', '.ropeproject/', '__pycache__/',
    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

'''

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons']
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''




[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = './install.sh'
hook_add = '''
  set hidden
  let g:LanguageClient_serverCommands = {
    \ 'python' : ['/usr/bin/pyls'],
    \ 'c' : ['/usr/bin/clangd'],
    \ 'cpp' : ['/usr/bin/clangd']
  \}
  let g:LanguageClient_autostart = 1
  nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
  '''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'




[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-devicons']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'onedark'
  '''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  let g:onedark_hide_endofbuffer = 1
  let g:onedark_terminal_italics = 1
  '''

[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
  let g:solarized_visibility = 'high'
  let g:solarized_termtrans = 1
  let g:solarized_term_italics = 1
'''


