[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'itchyny/vim-parenmatch'


[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_add = '''
  let g:suda_smart_edit = 1
'''


[[plugins]]
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua require("impatient")
'''

[[plugins]]
repo = 'folke/noice.nvim'
depends = ['nui.nvim']
hook_add = '''
lua << EOF
  local noice = require("noice")
  noice.setup({})
EOF
'''
[[plugins]]
repo = 'MunifTanjim/nui.nvim'
[[plugins]]
repo = 'rcarriga/nvim-notify'


[[plugins]]
repo = 'vim-denops/denops.vim'



# {{{ ColorScheme
# [[plugins]]
# repo = 'lifepillar/vim-solarized8'
[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
  let g:gruvbox_italicize_strings = 0
  let g:gruvbox_plugin_hi_groups = 0
  let g:gruvbox_filetype_hi_groups = 1
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
  let g:everforest_background = 'medium'
  let g:everforest_enable_italic = 1
  let g:everforest_better_performance = 1
'''

[[plugins]]
repo = 'niuez/gekkou.vim'
# }}}




[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''
