[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['vim-devicons']
hook_add = '''
  nmap [denite] <Nop>
  map <C-j> [denite]

  "カレントディレクトリ内のファイル検索"
  nmap <silent> [denite]<C-p> :<C-u>Denite -mode=normal file_rec
  "プレビュー付きgrep"
  nmap <silent> [denite]<C-g> :<C-u>Denite -auto-preview -mode=normal grep<CR>


  "検索対象外のファイル指定"
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', '.ropeproject/', '__pycache__/',
    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

  '''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  set completeopt+=noinsert
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons']
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''


[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes','vim-devicons']
hook_add = '''
  let g:airline_powerline_fonts = 0
  let g:airline_theme = 'luna'
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#ale#error_symbol = 'E'
  let g:airline#extensions#ale#warning_symbol = 'W'
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#tabline#buffer_idx_format = {
  	\ '0': '0 ',
  	\ '1': '1 ',
  	\ '2': '2 ',
  	\ '3': '3 ',
  	\ '4': '4 ',
  	\ '5': '5 ',
  	\ '6': '6 ',
  	\ '7': '7 ',
  	\ '8': '8 ',
  	\ '9': '9 '
  	\}
  '''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_error = '!'
  let g:ale_sign_warning = '*'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_sign_column_always = 1

  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 'never'

  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0


  let g:ale_linters = {
  \   'python': ['flake8'],
  \   'c': ['clang'],
  \   'cpp': ['clang']
  \}

  let g:ale_fixers = {
  \   'python': ['yapf'],
  \   'c': ['clang-format'],
  \   'cpp': ['clang-format']
  \}

  let g:ale_fix_on_save = 1

  '''
