[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  call deoplete#custom#option({
    \'auto_complete_delay': 0,
    \'smart_case': v:true,
    \})

'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-lsp'
on_i = 1
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#lsp#handler_enabled = v:true
  let g:deoplete#lsp#use_icons_for_candidates = v:true
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_command = ['TableModeToggle']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_ft = ['python']
hook_source = '''
  let g:virtualenv_directory = '~/.local/share/virtualenvs'
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
depends = ['vim-table-mode']
hook_source = '''
  let g:markdown_minlines = 100
  let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'rust', 'cpp', 'c']
'''

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_source = '''
  let g:previm_open_cmd = 'firefox'
  let g:previm_enable_realtime = 1
  '''
