[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['vim-devicons']
hook_add = '''
  map <Space>d [denite]

  "キーバインド"
  nmap <silent> [denite]f :<C-u>Denite file/rec<CR>
  nmap <silent> [denite]g :<C-u>Denite grep<CR>
  nmap <silent> [denite]b :<C-u>Denite buffer<CR>
  "depend on LanguageClient-neovim
  nmap <silent> [denite]s :<C-u>Denite -auto-action="preview" documentSymbol<CR>
  nmap <silent> [denite]ws :<C-u>Denite -auto-action="preview" workspaceSymbol<CR>


  autocmd FileType denite call s:denite_my_setting()
  function! s:denite_my_setting()abort
    nnoremap <silent><buffer><expr> <CR>
    \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> p
    \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q
    \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
    \ denite#do_map('open_filter_buffer')
  endfunction

  let s:denite_win_width_percent = 0.85
  let s:denite_win_height_percent = 0.7

  call denite#custom#option('default', {
      \ 'split': 'floating',
      \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
      \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
      \ 'winheight': float2nr(&lines * s:denite_win_height_percent),
      \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_percent)) / 2),
      \ })

  autocmd FileType denite set winblend=10
  autocmd FileType denite-filter set winblend=10
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
hook_add = '''
  nmap <Space>f :<C-u>Defx -split=vertical -listed -resume -auto-cd -winwidth=40<CR>
  call defx#custom#option('_', {'columns': 'indent:icons:filename:type'})
  autocmd FileType defx call s:my_defx_setting()
  function! s:my_defx_setting() abort
    nnoremap <silent><buffer><expr> <CR> defx#async_action('drop')
    nnoremap <silent><buffer><expr> o defx#do_action('open_or_close_tree')
    nnoremap <silent><buffer><expr> v defx#do_action('drop', 'vsplit')
    nnoremap <silent><buffer><expr> s defx#do_action('drop', 'split')

    nnoremap <silent><buffer><expr> h defx#async_action('cd', ['..'])
    nnoremap <silent><buffer><expr> ~ defx#async_action('cd')

    nnoremap <silent><buffer><expr> nf defx#do_action('new_file')
    nnoremap <silent><buffer><expr> nd defx#do_action('new_directory')

    nnoremap <silent><buffer><expr> yy defx#do_action('copy')
    nnoremap <silent><buffer><expr> m defx#do_action('move')
    nnoremap <silent><buffer><expr> p defx#do_action('paste')

    nnoremap <silent><buffer><expr> d defx#do_action('remove')
    nnoremap <silent><buffer><expr> r defx#do_action('rename')
    nnoremap <silent><buffer><expr> q defx#do_action('quit')
  endfunction
'''


[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  let g:LanguageClient_serverCommands = {
    \ 'python' : ['/home/marimo-kd/.local/share/virtualenvs/.neovim-L4xtE3iV/bin/pyls'],
    \ 'rust': ['rustup','run','stable','rls'],
    \ 'c' : ['/usr/bin/clangd'],
    \ 'cpp' : ['/usr/bin/clangd'],
    \ 'objc' : ['/usr/bin/clangd']
  \}
  let g:LanguageClient_autostart = 1
  let g:LanguageClient_useFloatingHover = 1
  let g:LanguageClient_hoverPreview = "Always"

  nmap [LSP] <Nop>
  map <Space>l [LSP]
  nnoremap <silent> [LSP]h :<C-u>call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> [LSP]d :<C-u>call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent> [LSP]t :<C-u>call LanguageClient#textDocument_typeDefinition()<CR>
  nnoremap <silent> [LSP]r :<C-u>call LanguageClient#textDocument_rename()<CR>
  nnoremap <silent> [LSP]f :<C-u>call LanguageClient#textDocument_formatting()<CR>
'''

[[plugins]]
repo = 'deton/jasegment.vim'
hook_add = '''
  let g:jasegment#model = 'mecab'
  let g:jasegment#highlight = 0
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'machakann/vim-highlightedyank'


[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-devicons']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'one'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
hook_add = '''
  let g:defx_icons_enable_syntax_highlight = 1
  let g:defx_icons_column_length = 2
  let g:defx_icons_directory_icon = ''
  let g:defx_icons_mark_icon = '*'
  let g:defx_icons_parent_icon = ''
  let g:defx_icons_default_icon = ''
  let g:defx_icons_directory_symlink_icon = ''
  let g:defx_icons_root_opened_tree_icon = ''
  let g:defx_icons_nested_opened_tree_icon = ''
  let g:defx_icons_nested_closed_tree_icon = ''
'''

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
