[[plugins]]
repo = 'Shougo/dein.vim'



[[plugins]]
repo = 'itchyny/vim-parenmatch'



[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']



[[plugins]]
repo = 'Shougo/context_filetype.vim'



[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_add = '''
  let g:suda_smart_edit = 1
'''



[[plugins]]
repo = 'ncm2/float-preview.nvim'
if = 'has("nvim") && !(exists("g:use_ddc") && g:use_ddc)'
hook_add = '''
  let g:float_preview#docked=1
'''



[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
if = 'has("nvim")'



[[plugins]]
repo = 'vim-denops/denops.vim'



# {{{ ColorScheme
# [[plugins]]
# repo = 'lifepillar/vim-solarized8'
[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
  let g:gruvbox_italicize_strings = 0
  let g:gruvbox_plugin_hi_groups = 0
  let g:gruvbox_filetype_hi_groups = 1
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
# }}}




[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''
