[[plugins]]
repo = 'Shougo/dein.vim'



[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''



[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
  let g:gruvbox_italicize_strings = 0
'''



[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'
