#{{{ Core
[[plugins]]
repo = 'Shougo/ddu.vim'
on_func = 'ddu#start'
hook_add = '''
  " launcher
  nnoremap <Space>d <cmd>Ddu source<CR>
  " file
  nnoremap <Space>f <cmd>Ddu file_rec<CR>
  " buffer                                       
  nnoremap <Space>b <cmd>Ddu buffer<CR>
  " live grep
  nnoremap <Space>g <cmd>call ddu#start({
  \ 'name': 'file',
  \ 'volatile': v:true,
  \ 'sources': [{'name': 'rg', 'options': {'matchers': []}}],
  \ 'uiParams': {
  \   'ff': {
  \     'ignoreEmpty': v:false,
  \     'autoResize': v:false,
  \     }
  \   },
  \ })<CR>

  "filer
  nnoremap <Space>e <cmd>call ddu#start({
  \ 'name': 'filer',
  \ 'uiParams': {'filer': {'search': expand('%:p')}},
  \ })<CR>
'''
hook_source = '''
  "ui
  call ddu#custom#patch_global({
  \ 'ui': 'ff',
  \ 'uiParams': {
  \   'ff': {
  \     'floatingBorder': 'rounded',
  \     'previewFloating': v:true,
  \     'displaySourceName': 'long',
  \     'split': 'floating',
  \     'prompt': '>',
  \     'winCol': &columns / 6,
  \     'winHeight': &lines / 2,
  \     'winRow': &lines / 4,
  \     'winWidth': &columns / 3 * 2,
  \     }
  \   }
  \ })
  call ddu#custom#patch_local('filer', {
  \ 'ui': 'filer',
  \ 'uiParams': {
  \   'filer': {
  \     'winWidth': 40,
  \     'split': 'vertical',
  \     'splitDirection': 'topleft',
  \   },
  \ },
  \ 'sources': [
  \   {
  \     'name': 'file',
  \     'params': {},
  \   },
  \ ],
  \ })
  "sources
  call ddu#custom#patch_global({
  \ 'sourceParams': {
  \   'rg': {
  \     'args': ['--json'],
  \     }
  \   }
  \ })
  "filter
  call ddu#custom#patch_global({
  \ 'sourceOptions': {
  \   '_': {
  \     'matchers': ['matcher_fzf'],
  \     'columns': ['icon_filename'],
  \     },
  \   },
  \ })
  "kind default action
  call ddu#custom#patch_global({
  \ 'kindOptions': {
  \   'file': {
  \     'defaultAction': 'open',
  \     },
  \   'action': {
  \     'defaultAction': 'do',
  \     },
  \   'help': {
  \     'defaultAction': 'vsplit',
  \     },
  \   'source': {
  \     'defaultAction': 'execute',
  \     },
  \   },
  \ })
'''
#}}}

#{{{ UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-ff = '''
  setlocal cursorline
  set winblend=50
  nnoremap <buffer><silent> <CR>
  \ <cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
  \ <cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> a
  \ <cmd>call ddu#ui#ff#do_action('chooseAction')
  nnoremap <buffer><silent> p
  \ <cmd>call ddu#ui#ff#do_action('preview')
  nnoremap <buffer><silent> i
  \ <cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> x
  \ <cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> q
  \ <cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer><silent> <ESC>
  \ <cmd>call ddu#ui#ff#do_action('quit')<CR>

  if b:ddu_ui_name ==# 'help'
    nnoremap <buffer><silent> v
    \ <cmd>call ddu#ui#ff#do_action('itemAction',
    \ {'name': 'vsplit'})<CR>
  else
    nnoremap <buffer><silent> v
    \ <cmd>call ddu#ui#ff#do_action('itemAction',
    \ {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
  endif
'''
ddu-ff-filter = '''
  set winblend=50
  inoremap <buffer><silent> <CR> <ESC><cmd>close<CR>
  nnoremap <buffer><silent> <CR> <ESC>close<CR>
  nnoremap <buffer><silent> q
  \ <cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer><silent> <ESC>
  \ <cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hook_add = '''
  function! s:open_with_ddu() abort
    let path = expand('%:p')
    if !isdirectory(path)
      return
    endif
    call ddu#start({
    \ 'name': 'filer',
    \ 'uiParams': {'filer': {'search': path}}
    \})
  endfunction
  augroup open-ddu-dir
    autocmd!
    autocmd BufEnter * ++nested call s:open_with_ddu()
  augroup END
'''
[plugins.ftplugin]
ddu-filer = '''
  nnoremap <buffer><silent><expr> <CR>
  \ ddu#ui#filer#is_directory() ?
  \ "<cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow'})<CR>" :
  \ "<cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>"

  nnoremap <buffer><silent> <ESC>
  \ <cmd>call ddu#ui#filer#do_action('quit')<CR>

  nnoremap <buffer><silent> q
  \ <cmd>call ddu#ui#filer#do_action('quit')<CR>

  nnoremap <buffer><silent> ..
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow', 'params': {'path': '..'}})<CR>

  nnoremap <buffer><silent> d
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'delete'})<CR>

  nnoremap <buffer><silent> r
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'rename'})<CR>

  nnoremap <buffer><silent> mv
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'move'})<CR>

  nnoremap <buffer><silent> t
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newFile'})<CR>

  nnoremap <buffer><silent> mk
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newDirectory'})<CR>

  nnoremap <buffer><silent> yy
  \ <cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'yank'})<CR>
'''


#}}}

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = ['ddu.vim']
on_cmd = ['Ddu']

#{{{ Filter
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'
#}}}

#{{{ Source
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'
# NOTE: including action kind

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'
# NOTE: including help kind

[[plugins]]
repo = '4513ECHO/ddu-source-source'
on_source = 'ddu.vim'
# NOTE: including source kind
#}}}

#{{{ Kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'
#}}}

# {{{ Column
[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'
#}}}
