[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nmap [denite] <Nop>
  map <C-j> [denite]

  " プロジェクト内のファイル検索"
  nmap <silent> [denite]<C-P> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
  " ファイル内の関数/クラス等の検索
  nmap <silent> [denite]<C-O> :<C-u>Denite outline -highlight-mode-insert=Search<CR>

  "検索対象外のファイル指定"
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', '.ropeproject/', '__pycache__/',
    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

  '''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  '''
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-thmes']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'base16'
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#ale#error_symbol = 'E'
  let g:airline#extensions#ale#warning_symbol = 'W'
  '''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
