[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['vim-devicons']
hook_add = '''
  nmap [denite] <Nop>
  map <C-j> [denite]

  " プロジェクト内のファイル検索"
  nmap <silent> [denite]<C-P> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
  " ファイル内の関数/クラス等の検索
  nmap <silent> [denite]<C-O> :<C-u>Denite outline -highlight-mode-insert=Search<CR>

  "検索対象外のファイル指定"
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', '.ropeproject/', '__pycache__/',
    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

  '''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons']
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''


[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes','vim-devicons']
hook_add = '''
  let g:airline_powerline_fonts = 0
  let g:airline_theme = 'luna'
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#ale#error_symbol = 'E'
  let g:airline#extensions#ale#warning_symbol = 'W'
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#tabline#buffer_idx_format = {
  	\ '0': '0 ',
  	\ '1': '1 ',
  	\ '2': '2 ',
  	\ '3': '3 ',
  	\ '4': '4 ',
  	\ '5': '5 ',
  	\ '6': '6 ',
  	\ '7': '7 ',
  	\ '8': '8 ',
  	\ '9': '9 '
  	\}
  '''
