[[plugins]]
repo = 'Shougo/dein.vim'



[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''



[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
  let g:gruvbox_italicize_strings = 0
'''



[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'



[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''



[[plugins]]
repo = 'hoob3rt/lualine.nvim'
hook_add = '''
lua << EOF
  local lualine = require('lualine')
  lualine.options.theme = 'gruvbox'
  lualine.sections.lualine_z = { 
    {
      'diagnostics',
      sources = {'nvim_lsp'},
    },
    {
      'location',
    }
  }
  lualine.status()
EOF
'''
