[[plugins]]
repo = 'Shougo/dein.vim'



[[plugins]]
repo = 'itchyny/vim-parenmatch'



[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']



[[plugins]]
repo = 'Shougo/context_filetype.vim'



[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_add = '''
  let g:suda_smart_edit = 1
'''



[[plugins]]
repo = 'vim-denops/denops.vim'



[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
  let g:gruvbox_italicize_strings = 0
  let g:gruvbox_plugin_hi_groups = 0
  let g:gruvbox_filetype_hi_groups = 0
'''



# [[plugins]]
# repo = 'lifepillar/vim-solarized8'



[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''
