import = [
  "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
];

[window]
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[font]
normal = {family = "Sarasa Gothic Term J", style = "Regular"}

