[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
on_event = ['CmdlineEnter', 'InsertEnter', 'CursorHold']
hook_add = '''
nnoremap : <cmd>call CommandlinePre()<CR>:
function! CommandlinePre() abort
  " Note: This disables default command line completion!
  let b:prev_buffer_config = ddc#custom#get_buffer()
  
  call ddc#custom#patch_buffer('sourceOptions', #{
  \ _: #{
  \   keywordPattern: '[0-9a-zA-Z_:#-]*',
  \ },
  \ })

  autocmd User DDCCmdlineLeave ++once call CommandlinePost()

  " Enable command line completion
  call ddc#enable_cmdline_completion()
endfunction
function! CommandlinePost() abort
  " Restore sources
  if exists('b:prev_buffer_config')
    call ddc#custom#set_buffer(b:prev_buffer_config)
    unlet b:prev_buffer_config
  endif
endfunction
'''
hook_source = '''
inoremap <C-n> <cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-y> <cmd>call pum#map#confirm()<CR>
inoremap <expr> <C-e> pum#visible()
  \ ? '<cmd>call pum#map#cancel()<CR>'
  \ : '<End>'
inoremap <C-Space> <cmd>call ddc#map#manual_complete()<CR>

inoremap <expr> <Tab> denippet#jumpable() ? '<Plug>(denippet-jump-next)' : '<Tab>'
inoremap <expr> <S-Tab> denippet#jumpable(-1) ? '<Plug>(denippet-jump-prev)' : '<S-Tab>'
snoremap <expr> <Tab> denippet#jumpable() ? '<Plug>(denippet-jump-next)' : '<Tab>'
snoremap <expr> <S-Tab> denippet#jumpable(-1) ? '<Plug>(denippet-jump-prev)' : '<S-Tab>'

cnoremap <C-n>   <cmd>call pum#map#insert_relative(+1)<CR>
cnoremap <C-p>   <cmd>call pum#map#insert_relative(-1)<CR>
cnoremap <C-y>   <cmd>call pum#map#confirm()<CR>
cnoremap <expr> <C-e> pum#visible()
      \ ? '<cmd>call pum#map#cancel()<CR>'
      \ : '<End>'
cnoremap <C-Space> <cmd>call ddc#map#manual_complete()<CR>

call ddc#custom#patch_global(#{
  \ autoCompleteEvents: [
  \   'InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineEnter', 'CmdlineChanged',
  \ ],
  \ backspaceCompletion: v:true,
  \ ui: 'pum',
  \ sources: ['lsp', 'denippet', 'around', 'file'],
  \ cmdlineSources: {
  \   ':': ['cmdline', 'around'],
  \   '@': ['cmdline', 'around', 'file'],
  \   '>': ['cmdline', 'around', 'file'],
  \   '/': ['around',],
  \   '?': ['around',],
  \   '-': ['around',],
  \   '=': ['input',],
  \ },
  \ sourceOptions: #{
  \   _: #{
  \     ignoreCase: v:true,
  \     matchers: ['matcher_fuzzy'],
  \     sorters : ['sorter_fuzzy'],
  \     converters: ['converter_fuzzy'],
  \     timeout: 1000,
  \   },
  \   around: #{mark: '[A]',
  \             matchers: ['matcher_head', 'matcher_length'],
  \             converters: ['converter_remove_overlap'],},
  \   buffer: #{mark: '[B]',
  \             matchers: ['matcher_head', 'matcher_length'],
  \             converters: ['converter_remove_overlap'],},
  \   cmdline: #{mark: '[cmd]', forceCompletionPattern: "\\S/\\S*|\\.\\w*",},
  \   cmdline-history: #{mark: '[cmd]',
  \                      matchers: ['matcher_head', 'matcher_length'],
  \                      converters: ['converters_remove_overlap']},
  \   file: #{mark: '[f]', isVolatile: v:true, forceCompletionPattern: '\S/\S*',},
  \   input: #{mark: '[input]'},
  \   necovim: #{mark: '[neco]'},
  \   nvim-lua: #{mark: '[lua]', forceCompletionPattern: '\.\w*'},
  \   lsp: #{mark: '[lsp]', 
  \          keywordPattern: '\k+',
  \          forceCompletionPattern: '\.\w*|::\w*|->\w*',
  \          dup: 'keep',
  \          sorters: ['sorter_fuzzy', 'sorter_lsp-kind'],
  \          converters: ['converter_fuzzy', 'converter_kind_labels'],
  \          minAutoCompleteLength: 1,},
  \   skkeleton: #{mark: '[skk]',
  \                matchers: [],
  \                sorters: [],
  \                converters: [],
  \                minAutoCompleteLength: 2,
  \                isVolatile: v:true,},
  \   vsnip: #{mark: '[vsnip]'},
  \   denippet: #{mark: '[snip]'},
  \   shell-native: #{mark: '[zsh]', isVolatile: v:true, forceCompletionPattern: '\S/\S*',},
  \ },
  \ sourceParams: #{
  \   buffer: #{
  \     requireSameFiletype: v:false,
  \     limitBytes: 500000,
  \     fromAltBuf: v:true,
  \     fourceCollect: v:true,
  \   },
  \   lsp: #{
  \     snippetEngine: denops#callback#register({
  \           body -> denippet#anonymous(body)
  \     }),
  \     enableResolveItem: v:true,
  \     enableAdditionalTextEdit: v:true,
  \   },
  \ },
  \ filterParams: #{
  \   matcher_fuzzy: #{
  \     splitMode: 'word',
  \   },
  \   converter_kind_labels: #{
  \     kindLabels: #{
  \       Text: "",
  \       Method: "",
  \       Function: "",
  \       Constructor: "",
  \       Field: "",
  \       Variable: "",
  \       Class: "",
  \       Interface: "",
  \       Module: "",
  \       Property: "",
  \       Unit: "",
  \       Value: "",
  \       Enum: "",
  \       Keyword: "",
  \       Snippet: "",
  \       Color: "",
  \       File: "",
  \       Reference: "",
  \       Folder: "",
  \       EnumMember: "",
  \       Constant: "",
  \       Struct: "",
  \       Event: "",
  \       Operator: "",
  \       TypeParameter: ""
  \     },
  \     kindHlGroups: #{
  \       Method: "Function",
  \       Function: "Function",
  \       Constructor: "Function",
  \       Field: "Identifier",
  \       Variable: "Identifier",
  \       Class: "Structure",
  \       Interface: "Structure"
  \     }
  \   }
  \ }
  \ })
call ddc#custom#patch_filetype(
  \ ['zsh', 'deol'], 'sources',
  \ ['shell-native', 'file']
  \)
call ddc#custom#patch_filetype(
  \ ['vim'], 'sources',
  \ ['necovim', 'around', 'file']
  \ )
call ddc#enable_terminal_completion()
call ddc#enable(#{
  \ context_filetype: has('nvim') ? 'treesitter' : 'context_filetype',
  \ })
'''
hook_post_update = 'call ddc#set_static_import_path()'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = '''
  call pum#set_option(#{
  \  auto_select: v:false,
  \  border: 'none',
  \  commit_characters: ['.'],
  \  follow_cursor: v:true,
  \  max_height: 8,
  \  max_width: 80,
  \  preview: v:false,
  \  preview_border: 'single',
  \  preview_height: 10,
  \  preview_width: 80,
  \ })
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/denippet.vim'
on_source = 'ddc.vim'
hook_source = '''
let dir = stdpath('config') . '/snippet/'
for file in glob(dir . '*.*', 1, 1)
  call denippet#load(file)
endfor
'''

# ddc sources
[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
if = false
on_source = 'ddc.vim'
depends = 'vim-vsnip'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-input'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'
if = 'has("nvim")'
depends = 'ddc-source-lsp'
on_source = 'nvim-lspconfig'
lua_source = 'require("ddc_source_lsp_setup").setup{}'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
if = 'has("nvim")'
on_source = 'ddc.vim'
depends = ['nvim-lspconfig']

[[plugins]]
repo = 'Shougo/ddc-source-shell-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lua'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-omni'
if = false
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_source = 'ddc.vim'

# ddc matchers
[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_length'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

# ddc sorters
[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

# ddc converters
[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'ddc.vim'
hook_source = 'call signature_help#enable()'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
if = false
on_source = 'ddc.vim'
hook_source = 'call popup_preview#enable()'
