[ftplugin]
python = '''
  setlocal shiftwidth=4
  setlocal softtabstop=4
  setlocal tabstop=4
  setlocal expandtab
'''
satysfi = '''
  setlocal autoindent
  setlocal indentexpr=
  setlocal equalprg=
  setlocal shiftwidth=2
  setlocal softtabstop=2
  setlocal tabstop=2
  setlocal suffixesadd+=.saty,.satyh,.satyg
  setlocal matchpairs+=<:>
  "setlocal foldmethod=indent
  setlocal foldnestmax=4
  setlocal foldminlines=5
'''
