[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_add = '''
  let g:suda_smart_edit = 1
'''

[[plugins]]
repo = 'folke/noice.nvim'
if = 'has("nvim")'
depends = ['nui.nvim', 'nvim-notify']
lua_add = '''
  local noice = require("noice")
  noice.setup({
    lsp = {
      -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
      },
    },
    -- you can enable a preset for easier configuration
    presets = {
      long_message_to_split = true, -- long messages will be sent to a split
      lsp_doc_border = false, -- add a border to hover docs and signature help
    },
  })
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'rcarriga/nvim-notify'

[[plugins]]
repo = 'rebelot/heirline.nvim'
if = 'has("nvim")'
lua_add = '''
  require('plugins.heirline')
'''

[[plugins]]
repo = 'folke/flash.nvim'
#on_lua = 'flash'
if = 'v:false'
hook_add = '''
  lua require('flash').setup()
  xnoremap <silent><Leader>w <cmd>lua require('flash').jump()<CR>
  nnoremap <silent><Leader>w <cmd>lua require('flash').jump()<CR>
  onoremap <silent><Leader>w <cmd>lua require('flash').jump()<CR>
  xnoremap <silent><Leader>W <cmd>lua require('flash').treesitter()<CR>
  nnoremap <silent><Leader>W <cmd>lua require('flash').treesitter()<CR>
  onoremap <silent><Leader>W <cmd>lua require('flash').treesitter()<CR>
  cnoremap <silent><C-s> <cmd>lua require('flash').toggle()<CR>
  function! s:init_flash_highlight() abort
    highlight link FlashCurrent Cursor
    highlight link FlashBackdrop HopUnmatched
    highlight link FlashMatch HopNextKey
    highlight link FlashLabel HopNextKey1
  endfunction
  augroup FlashHighlight
    autocmd!
    autocmd ColorScheme * call s:init_flash_highlight()
  augroup END
'''

# {{{ ColorScheme
#[[plugins]]
#repo = 'lifepillar/vim-solarized8'
[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
  let g:gruvbox_italicize_strings = 0
  let g:gruvbox_plugin_hi_groups = 0
  let g:gruvbox_filetype_hi_groups = 1
'''

#[[plugins]]
#repo = 'EdenEast/nightfox.nvim'
#
#[[plugins]]
#repo = 'folke/tokyonight.nvim'
#
#[[plugins]]
#repo = 'savq/melange'
#
#[[plugins]]
#repo = 'sainnhe/everforest'
#hook_add = '''
#  let g:everforest_background = 'medium'
#  let g:everforest_enable_italic = 1
#  let g:everforest_better_performance = 1
#'''
#
#[[plugins]]
#repo = 'niuez/gekkou.vim'
#
#[[plugins]]
#repo = 'marko-cerovac/material.nvim'
#lua_add = '''
#  vim.g.material_style = 'darker'
#  require('material').setup{
#    contrast = {
#      terminal = true,
#      floating_windows = true,
#    },
#    plugins = {
#      "hop",
#      "nvim-web-devicons",
#    },
#  }
#'''
[[plugins]]
repo = 'catppuccin/nvim'
name = 'catppuccin'
lua_add = '''
  require('catppuccin').setup{
    flavour = 'macchiato',
    integrations = {
      alpha = false,
      dashboard = false,
      hop = false,
      notify = true,
      native_lsp = {
        enabled = true,
      },
      treesitter = true,
      telescope = false,
    },
  }
'''
# }}}

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[plugins.ftplugin]
python = '''
  setlocal shiftwidth=4
  setlocal softtabstop=4
  setlocal tabstop=4
  setlocal expandtab
'''
satysfi = '''
  setlocal autoindent
  setlocal indentexpr=
  setlocal equalprg=
  setlocal shiftwidth=2
  setlocal softtabstop=2
  setlocal tabstop=2
  setlocal suffixesadd+=.saty,.satyh,.satyg
  setlocal matchpairs+=<:>
  "setlocal foldmethod=indent
  setlocal foldnestmax=4
  setlocal foldminlines=5
'''
